services:
  uvicorn-service:
    container_name: uvicorn-service
    build: uvicorn
    ports:
      - 8000:8000
    
  proxy:
    container_name: auth-proxy
    build: proxy
    ports:
      - 80:80
    depends_on:
      - uvicorn-service
